// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8QUcslIrABtAJoipNePvFHwsp1QZtWwk',
    appId: '1:848287561110:web:bd2e3c27eb909c91fa19b7',
    messagingSenderId: '848287561110',
    projectId: 'vibely-official',
    authDomain: 'vibely-official.firebaseapp.com',
    storageBucket: 'vibely-official.firebasestorage.app',
    measurementId: 'G-E0RELRDN8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDirmj4lYma5kjvKDRgHjQFf-UUO7QSVw',
    appId: '1:848287561110:android:1e181df3069c85c3fa19b7',
    messagingSenderId: '848287561110',
    projectId: 'vibely-official',
    storageBucket: 'vibely-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB_Mqyv6NBviHWpDqyLr0kGAD19rYrxP0',
    appId: '1:848287561110:ios:38b070b68239cedefa19b7',
    messagingSenderId: '848287561110',
    projectId: 'vibely-official',
    storageBucket: 'vibely-official.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB_Mqyv6NBviHWpDqyLr0kGAD19rYrxP0',
    appId: '1:848287561110:ios:38b070b68239cedefa19b7',
    messagingSenderId: '848287561110',
    projectId: 'vibely-official',
    storageBucket: 'vibely-official.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8QUcslIrABtAJoipNePvFHwsp1QZtWwk',
    appId: '1:848287561110:web:8554327a6af10589fa19b7',
    messagingSenderId: '848287561110',
    projectId: 'vibely-official',
    authDomain: 'vibely-official.firebaseapp.com',
    storageBucket: 'vibely-official.firebasestorage.app',
    measurementId: 'G-3HVLZ9BZNT',
  );
}
